# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Badges Homepage
email: badges@badgealliance.org
description: >
  Get recognition for learning that happens anywhere. Then share it on the
  places that matter. A digital badge is an online representation of a skill
  you’ve earned.
baseurl: "/openbadges.org-static" # the subpath of your site, e.g. /blog
url: "http://openbadges.github.io" # the base hostname & protocol for your site
twitter_username: openbadges
github_username:  openbadges

# Build settings
markdown: kramdown
encoding: UTF-8