# Config for production build to install on master
# jekyll build --config _config-production.yml

# Site settings
title: Open Badges Homepage
email: badges@badgealliance.org
description: >
  Get recognition for learning that happens anywhere. Then share it on the
  places that matter. A digital badge is an online representation of a skill
  you’ve earned.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://openbadges.org" # the base hostname & protocol for your site
twitter_username: openbadges
github_username:  openbadges

# Build settings
markdown: kramdown
encoding: UTF-8

gems:
  - octopress-autoprefixer

sass:
  style: compressed

exclude: ['README.md', 'package.json', 'Gemfile', 'Gemfile.lock']
